// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN5gkilXUxpk5GRsiiW7vUPYemNNaOaDg',
    appId: '1:605277296015:web:3329cd7000361a7ab967fa',
    messagingSenderId: '605277296015',
    projectId: 'newestdelivery',
    authDomain: 'newestdelivery.firebaseapp.com',
    storageBucket: 'newestdelivery.firebasestorage.app',
    measurementId: 'G-JJQ7Q0STGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR0sVj-0s2EF73WcHio5sIQwqECX-aLsM',
    appId: '1:605277296015:android:be9840894d834f5eb967fa',
    messagingSenderId: '605277296015',
    projectId: 'newestdelivery',
    storageBucket: 'newestdelivery.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAedjiHjqR8l3BhpbYfORAWScb13BmWkrE',
    appId: '1:605277296015:ios:84c2102adccaadc5b967fa',
    messagingSenderId: '605277296015',
    projectId: 'newestdelivery',
    storageBucket: 'newestdelivery.firebasestorage.app',
    iosBundleId: 'com.example.deliveryAss',
  );

}